// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2riAGniqnbiiciSKWw3ors7DM_iB5Gyk',
    appId: '1:307452196856:web:e7e891a1fef8309f68080d',
    messagingSenderId: '307452196856',
    projectId: 'ecommerce-project-ec788',
    authDomain: 'ecommerce-project-ec788.firebaseapp.com',
    storageBucket: 'ecommerce-project-ec788.firebasestorage.app',
    measurementId: 'G-K4GE8767DW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEZe81JoUOeA38HoVMoSpu1WJHcQukEs0',
    appId: '1:307452196856:android:a0e6abea285dc15f68080d',
    messagingSenderId: '307452196856',
    projectId: 'ecommerce-project-ec788',
    storageBucket: 'ecommerce-project-ec788.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2bsbwTNDYWnypBICRC_LZXElF2YLhfrI',
    appId: '1:307452196856:ios:7894f3fdf6f292cf68080d',
    messagingSenderId: '307452196856',
    projectId: 'ecommerce-project-ec788',
    storageBucket: 'ecommerce-project-ec788.firebasestorage.app',
    androidClientId: '307452196856-4pjp0sd3bb12t71gv7joicqoj3m5hrln.apps.googleusercontent.com',
    iosClientId: '307452196856-0b64u7ir9el0dcntnh3i1c12rn4728hj.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2bsbwTNDYWnypBICRC_LZXElF2YLhfrI',
    appId: '1:307452196856:ios:7894f3fdf6f292cf68080d',
    messagingSenderId: '307452196856',
    projectId: 'ecommerce-project-ec788',
    storageBucket: 'ecommerce-project-ec788.firebasestorage.app',
    androidClientId: '307452196856-4pjp0sd3bb12t71gv7joicqoj3m5hrln.apps.googleusercontent.com',
    iosClientId: '307452196856-0b64u7ir9el0dcntnh3i1c12rn4728hj.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2riAGniqnbiiciSKWw3ors7DM_iB5Gyk',
    appId: '1:307452196856:web:888d743a14d8010c68080d',
    messagingSenderId: '307452196856',
    projectId: 'ecommerce-project-ec788',
    authDomain: 'ecommerce-project-ec788.firebaseapp.com',
    storageBucket: 'ecommerce-project-ec788.firebasestorage.app',
    measurementId: 'G-HR3YL7NK47',
  );
}
